=== helenkourilionok/Task2.2-XML-XSD-/bin/by/training/task2/xml/menu.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema targetNamespace="http://www.training.by/Task2/menu"  
	xmlns="http://www.w3.org/2001/XMLSchema" 
	xmlns:tns="http://www.training.by/Task2/menu">
	<element name="menu">
    	<complexType>
    		<sequence>
    			<element name="list-dishes" type="tns:Dishes" minOccurs="1" maxOccurs="unbounded"/>
    		</sequence>
    	</complexType>
    </element>

	<complexType name="Dishes">
		<sequence>
			<element name="food" type="tns:Food" minOccurs="1" maxOccurs="unbounded" />
		</sequence>
		<attribute name="nameListDishes"  type="tns:Name" use="required"/>
		<attribute name="id"  type="tns:UniqueId" use="required"/>
	</complexType>
	
	<simpleType name="Name">
		<restriction base="string">
			<enumeration value="cold collationes"></enumeration>
			<enumeration value="hot collationes"></enumeration>
			<enumeration value="breakfast dishes"></enumeration>
		</restriction>
	</simpleType>
	
	<complexType name="Food">
		<sequence>
			<element name="name" type="string"/>
			<element name="description" type="string"/>
			<element name="portion" type="string"/>
			<element name="price" type="positiveInteger"/>
		</sequence>
		<attribute name="id" type="tns:Id" use="required"/>
	</complexType>
	
	<simpleType name="UniqueId">
	<restriction base="ID">
		<pattern value="[a-z]{2}[0-9]{1}"/>
	</restriction>
	</simpleType>
	
	<simpleType name="Id">
		<restriction base="positiveInteger">
			<minInclusive value="1"/>
			<maxInclusive value="20"/>
		</restriction>
	</simpleType>
</schema>

=== helenkourilionok/Task2.2-XML-XSD-/src/by/training/task2/xml/menu.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:menu xmlns:tns="http://www.training.by/Task2/menu" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.training.by/Task2/menu menu.xsd ">
  <list-dishes id="id1" nameListDishes="cold collationes">
    <food id="1">
      <name>name</name>
      <description>description</description>
      <portion>portion</portion>
      <price>1</price>
    </food>
  </list-dishes>
  <list-dishes id="id2" nameListDishes="hot collationes">
    <food id="1">
      <name>name</name>
      <description>description</description>
      <portion>portion</portion>
      <price>1</price>
    </food>
    <food id="2">
      <name>name2</name>
      <description>description2</description>
      <portion>portion2</portion>
      <price>2</price>
    </food>
  </list-dishes>
  <list-dishes id="id3" nameListDishes="breakfast dishes">
  	<food id="1">
      <name>name3</name>
      <description>description3</description>
      <portion>portion3</portion>
      <price>3</price>
    </food>
  </list-dishes>
</tns:menu>
